<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ftw637-01" name="p01_core_runner.Ex01RememberingDataBetweenTests" tests="2" failures="1" timestamp="30 Mar 2016 07:21:32 GMT" time="0.002" errors="0">
  <testcase name="shouldIncrementANumberOneTime" time="0.001" classname="p01_core_runner.Ex01RememberingDataBetweenTests">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at p01_core_runner.Ex01RememberingDataBetweenTests.shouldIncrementANumberOneTime(Ex01RememberingDataBetweenTests.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.infinitest.testrunner.JUnit4Runner.runTestNGTest(JUnit4Runner.java:83)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:63)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:70)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:112)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:89)
]]>
    </failure>
  </testcase> <!-- shouldIncrementANumberOneTime -->
  <testcase name="shouldAlsoIncrementANumberOneTime" time="0.001" classname="p01_core_runner.Ex01RememberingDataBetweenTests"/>
</testsuite> <!-- p01_core_runner.Ex01RememberingDataBetweenTests -->
